# -*- coding: utf-8 -*-
"""emolex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulY_kILpzsxtD0nLP70W_xP0fyLj4ZdB
"""

from nrclex import NRCLex

# Assign list of strings
st = "i have a feeling i kinda lost my best friend"
text = st.split()
print("Sample Sentence:", st)
#print(st) 
# Iterate through list
for i in range(len(text)):
 
    # Create object#
    emotion = NRCLex(text[i])
    for x in emotion.raw_emotion_scores:
      d[x] = d[x]+1
    # Classify emotion
    #print('\n',text[i],':', emotion.raw_emotion_scores)
val = sum(d.values()) 
print("Generated Scores:")
print("{")
for x in d:
  d[x] = d[x]/val   
  print(x,":",d[x])
print("}")